format_code_in_doc_comments = true
format_strings = true
imports_granularity = "Crate"
use_small_heuristics = "Max"
use_field_init_shorthand = true
version = "Two"
newline_style = "unix"
use_try_shorthand = true
unstable_features = true
error_on_line_overflow = true
format_macro_bodies = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
normalize_doc_attributes = true
wrap_comments = true